# Generated by Django 4.1.1 on 2022-10-04 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('things', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='thing',
            options={},
        ),
        migrations.AlterModelManagers(
            name='thing',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='thing',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='email',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='password',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='thing',
            name='username',
        ),
        migrations.AddField(
            model_name='thing',
            name='description',
            field=models.CharField(default='fgdfg', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='name',
            field=models.CharField(default='gfd', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='thing',
            name='quantity',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
